//
//  ListTasksPresenter.swift
//  CleanTodo
//
//  Created by Zaim Ramlan on 05/03/2018.
//  Copyright (c) 2018 zaimramlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTasksPresentationLogic {
  func presentFetchFromDataStoreResult(with response: ListTasksModels.FetchFromDataStore.Response)
  func presentSelectTaskResult(with response: ListTasksModels.SelectTask.Response)
}

class ListTasksPresenter: ListTasksPresentationLogic {
  weak var viewController: ListTasksDisplayLogic?

  // MARK: Fetch Data From DataStore
  
  func presentFetchFromDataStoreResult(with response: ListTasksModels.FetchFromDataStore.Response) {
    let viewModel = ListTasksModels.FetchFromDataStore.ViewModel(tasks: response.tasks)
    viewController?.displayFetchFromDataStoreResult(with: viewModel)
  }  
  
  // MARK: Use Case - Select Task
  
  func presentSelectTaskResult(with response: ListTasksModels.SelectTask.Response) {
    let viewModel = ListTasksModels.SelectTask.ViewModel(tasks: response.tasks)
    viewController?.displaySelectTaskResult(with: viewModel)
  }
}
