//
//  ListTasksModels.swift
//  CleanTodo
//
//  Created by Zaim Ramlan on 05/03/2018.
//  Copyright (c) 2018 zaimramlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListTasksModels {
    
    // MARK: Data Store Fetch
    
    enum FetchFromDataStore {
        struct Request {
        }
        
        struct Response {
            var tasks: [String]
        }
        
        struct ViewModel {
            var tasks: [String]
        }
    }
    
    // MARK: Use Cases
    
    enum SelectTask {
        struct Request {
            var task: String?
        }
        
        struct Response {
            var tasks: [String]
        }
        
        struct ViewModel {
            var tasks: [String]
        }
    }
}
