//
//  ListTasksWorker.swift
//  CleanTodo
//
//  Created by Zaim Ramlan on 06/03/2018.
//  Copyright (c) 2018 zaimramlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListTasksWorker {
    func fetchFromDataStore() -> [String] {
        return ["Task 1", "Task 2"]
    }
    
    func removeTask(_ task: String, from taskList: [String]) -> [String] {
        guard let index = taskList.index(of: task) else { return taskList }
        
        var tasks = taskList
        tasks.remove(at: index)
        return tasks
    }
}
