//
//  ListTasksPresenterTests.swift
//  CleanTodo
//
//  Created by Zaim Ramlan on 05/03/2018.
//  Copyright (c) 2018 zaimramlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//@testable import CleanTodo
//import XCTest
//
//class ListTasksPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: ListTasksPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupListTasksPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupListTasksPresenter()
//  {
//    sut = ListTasksPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class ListTasksDisplayLogicSpy: ListTasksDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: ListTasks.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = ListTasksDisplayLogicSpy()
//    sut.viewController = spy
//    let response = ListTasks.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}

